package func.autoinckey.dao;

import func.autoinckey.model.Customer;
import func.autoinckey.model.criteria.CustomerCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    long count(CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int deleteByCriteria(CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int deleteByPk(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int insertAll(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    List<Customer> selectByCriteria(CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    Customer selectByPk(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateByCriteria(@Param("record") Customer record, @Param("example") CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateAllByCriteria(@Param("record") Customer record, @Param("example") CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int update(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateAll(Customer record);
}