package func.alltype.dao;

import func.alltype.model.AllDataTypes;
import func.alltype.model.criteria.AllDataTypesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllDataTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    long count(AllDataTypesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int deleteByCriteria(AllDataTypesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int deleteByPk(Long typeBigint);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int insertAll(AllDataTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int insert(AllDataTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    List<AllDataTypes> selectByCriteria(AllDataTypesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    AllDataTypes selectByPk(Long typeBigint);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateByCriteria(@Param("record") AllDataTypes record, @Param("example") AllDataTypesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateAllByCriteria(@Param("record") AllDataTypes record, @Param("example") AllDataTypesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int update(AllDataTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateAll(AllDataTypes record);
}