package original.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import original.model.AllDataTypes;
import original.model.AllDataTypesExample;

public interface AllDataTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    long countByExample(AllDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int deleteByExample(AllDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int deleteByPrimaryKey(Long typeBigint);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int insert(AllDataTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int insertSelective(AllDataTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    List<AllDataTypes> selectByExampleWithBLOBs(AllDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    List<AllDataTypes> selectByExample(AllDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    AllDataTypes selectByPrimaryKey(Long typeBigint);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") AllDataTypes record, @Param("example") AllDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") AllDataTypes record, @Param("example") AllDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int updateByExample(@Param("record") AllDataTypes record, @Param("example") AllDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int updateByPrimaryKeySelective(AllDataTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AllDataTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_data_types
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    int updateByPrimaryKey(AllDataTypes record);
}