package original.model;

import java.math.BigDecimal;
import java.util.Date;

public class AllDataTypes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_bigint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Long typeBigint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_varchar
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private String typeVarchar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_tinyint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Byte typeTinyint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_smallint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Short typeSmallint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_mediumint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Integer typeMediumint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_int
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Integer typeInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_date
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Date typeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_float
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Float typeFloat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_double
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Double typeDouble;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_decimal
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private BigDecimal typeDecimal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_datetime
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Date typeDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_timestamp
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Date typeTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_time
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Date typeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_year
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Date typeYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_char
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private String typeChar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_tinytext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private String typeTinytext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_enum
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private String typeEnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_set
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private String typeSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_bool
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private Boolean typeBool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_text
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private String typeText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_tinyblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private byte[] typeTinyblob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_blob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private byte[] typeBlob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_mediumblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private byte[] typeMediumblob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_mediumtext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private String typeMediumtext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_longblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private byte[] typeLongblob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_longtext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private String typeLongtext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_binary
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private byte[] typeBinary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_data_types.type_varbinary
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    private byte[] typeVarbinary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_bigint
     *
     * @return the value of all_data_types.type_bigint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Long getTypeBigint() {
        return typeBigint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_bigint
     *
     * @param typeBigint the value for all_data_types.type_bigint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeBigint(Long typeBigint) {
        this.typeBigint = typeBigint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_varchar
     *
     * @return the value of all_data_types.type_varchar
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public String getTypeVarchar() {
        return typeVarchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_varchar
     *
     * @param typeVarchar the value for all_data_types.type_varchar
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeVarchar(String typeVarchar) {
        this.typeVarchar = typeVarchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_tinyint
     *
     * @return the value of all_data_types.type_tinyint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Byte getTypeTinyint() {
        return typeTinyint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_tinyint
     *
     * @param typeTinyint the value for all_data_types.type_tinyint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeTinyint(Byte typeTinyint) {
        this.typeTinyint = typeTinyint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_smallint
     *
     * @return the value of all_data_types.type_smallint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Short getTypeSmallint() {
        return typeSmallint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_smallint
     *
     * @param typeSmallint the value for all_data_types.type_smallint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeSmallint(Short typeSmallint) {
        this.typeSmallint = typeSmallint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_mediumint
     *
     * @return the value of all_data_types.type_mediumint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Integer getTypeMediumint() {
        return typeMediumint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_mediumint
     *
     * @param typeMediumint the value for all_data_types.type_mediumint
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeMediumint(Integer typeMediumint) {
        this.typeMediumint = typeMediumint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_int
     *
     * @return the value of all_data_types.type_int
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Integer getTypeInt() {
        return typeInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_int
     *
     * @param typeInt the value for all_data_types.type_int
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeInt(Integer typeInt) {
        this.typeInt = typeInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_date
     *
     * @return the value of all_data_types.type_date
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Date getTypeDate() {
        return typeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_date
     *
     * @param typeDate the value for all_data_types.type_date
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeDate(Date typeDate) {
        this.typeDate = typeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_float
     *
     * @return the value of all_data_types.type_float
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Float getTypeFloat() {
        return typeFloat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_float
     *
     * @param typeFloat the value for all_data_types.type_float
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeFloat(Float typeFloat) {
        this.typeFloat = typeFloat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_double
     *
     * @return the value of all_data_types.type_double
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Double getTypeDouble() {
        return typeDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_double
     *
     * @param typeDouble the value for all_data_types.type_double
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeDouble(Double typeDouble) {
        this.typeDouble = typeDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_decimal
     *
     * @return the value of all_data_types.type_decimal
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public BigDecimal getTypeDecimal() {
        return typeDecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_decimal
     *
     * @param typeDecimal the value for all_data_types.type_decimal
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeDecimal(BigDecimal typeDecimal) {
        this.typeDecimal = typeDecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_datetime
     *
     * @return the value of all_data_types.type_datetime
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Date getTypeDatetime() {
        return typeDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_datetime
     *
     * @param typeDatetime the value for all_data_types.type_datetime
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeDatetime(Date typeDatetime) {
        this.typeDatetime = typeDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_timestamp
     *
     * @return the value of all_data_types.type_timestamp
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Date getTypeTimestamp() {
        return typeTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_timestamp
     *
     * @param typeTimestamp the value for all_data_types.type_timestamp
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeTimestamp(Date typeTimestamp) {
        this.typeTimestamp = typeTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_time
     *
     * @return the value of all_data_types.type_time
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Date getTypeTime() {
        return typeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_time
     *
     * @param typeTime the value for all_data_types.type_time
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeTime(Date typeTime) {
        this.typeTime = typeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_year
     *
     * @return the value of all_data_types.type_year
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Date getTypeYear() {
        return typeYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_year
     *
     * @param typeYear the value for all_data_types.type_year
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeYear(Date typeYear) {
        this.typeYear = typeYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_char
     *
     * @return the value of all_data_types.type_char
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public String getTypeChar() {
        return typeChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_char
     *
     * @param typeChar the value for all_data_types.type_char
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeChar(String typeChar) {
        this.typeChar = typeChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_tinytext
     *
     * @return the value of all_data_types.type_tinytext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public String getTypeTinytext() {
        return typeTinytext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_tinytext
     *
     * @param typeTinytext the value for all_data_types.type_tinytext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeTinytext(String typeTinytext) {
        this.typeTinytext = typeTinytext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_enum
     *
     * @return the value of all_data_types.type_enum
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public String getTypeEnum() {
        return typeEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_enum
     *
     * @param typeEnum the value for all_data_types.type_enum
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeEnum(String typeEnum) {
        this.typeEnum = typeEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_set
     *
     * @return the value of all_data_types.type_set
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public String getTypeSet() {
        return typeSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_set
     *
     * @param typeSet the value for all_data_types.type_set
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeSet(String typeSet) {
        this.typeSet = typeSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_bool
     *
     * @return the value of all_data_types.type_bool
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public Boolean getTypeBool() {
        return typeBool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_bool
     *
     * @param typeBool the value for all_data_types.type_bool
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeBool(Boolean typeBool) {
        this.typeBool = typeBool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_text
     *
     * @return the value of all_data_types.type_text
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public String getTypeText() {
        return typeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_text
     *
     * @param typeText the value for all_data_types.type_text
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeText(String typeText) {
        this.typeText = typeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_tinyblob
     *
     * @return the value of all_data_types.type_tinyblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public byte[] getTypeTinyblob() {
        return typeTinyblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_tinyblob
     *
     * @param typeTinyblob the value for all_data_types.type_tinyblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeTinyblob(byte[] typeTinyblob) {
        this.typeTinyblob = typeTinyblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_blob
     *
     * @return the value of all_data_types.type_blob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public byte[] getTypeBlob() {
        return typeBlob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_blob
     *
     * @param typeBlob the value for all_data_types.type_blob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeBlob(byte[] typeBlob) {
        this.typeBlob = typeBlob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_mediumblob
     *
     * @return the value of all_data_types.type_mediumblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public byte[] getTypeMediumblob() {
        return typeMediumblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_mediumblob
     *
     * @param typeMediumblob the value for all_data_types.type_mediumblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeMediumblob(byte[] typeMediumblob) {
        this.typeMediumblob = typeMediumblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_mediumtext
     *
     * @return the value of all_data_types.type_mediumtext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public String getTypeMediumtext() {
        return typeMediumtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_mediumtext
     *
     * @param typeMediumtext the value for all_data_types.type_mediumtext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeMediumtext(String typeMediumtext) {
        this.typeMediumtext = typeMediumtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_longblob
     *
     * @return the value of all_data_types.type_longblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public byte[] getTypeLongblob() {
        return typeLongblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_longblob
     *
     * @param typeLongblob the value for all_data_types.type_longblob
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeLongblob(byte[] typeLongblob) {
        this.typeLongblob = typeLongblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_longtext
     *
     * @return the value of all_data_types.type_longtext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public String getTypeLongtext() {
        return typeLongtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_longtext
     *
     * @param typeLongtext the value for all_data_types.type_longtext
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeLongtext(String typeLongtext) {
        this.typeLongtext = typeLongtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_binary
     *
     * @return the value of all_data_types.type_binary
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public byte[] getTypeBinary() {
        return typeBinary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_binary
     *
     * @param typeBinary the value for all_data_types.type_binary
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeBinary(byte[] typeBinary) {
        this.typeBinary = typeBinary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_data_types.type_varbinary
     *
     * @return the value of all_data_types.type_varbinary
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public byte[] getTypeVarbinary() {
        return typeVarbinary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_data_types.type_varbinary
     *
     * @param typeVarbinary the value for all_data_types.type_varbinary
     *
     * @mbg.generated Thu Aug 16 13:09:50 CST 2018
     */
    public void setTypeVarbinary(byte[] typeVarbinary) {
        this.typeVarbinary = typeVarbinary;
    }
}