package org.nalby.yobatis.core.mybatis.factory;

import org.mybatis.generator.api.GeneratedJavaFile;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Interface;
import org.mybatis.generator.api.dom.java.TopLevelClass;
import org.nalby.yobatis.core.mybatis.YobatisJavaFile;

public interface JavaFileFactory {

    /**
     * Create the base dao interface which is extended by table specific DAOs.
     * @param introspectedTable the table.
     * @return the base dao java file.
     */
    YobatisJavaFile baseDaoInterface(IntrospectedTable introspectedTable);

    /**
     * Create implementing java file of the base dao.
     * @param introspectedTable the table.
     * @return the implementing java file
     */
    YobatisJavaFile baseDaoImpl(IntrospectedTable introspectedTable);

    /**
     * Create dao interface for the table {@code introspectedTable}.
     * @param interfaze the java Mapper generated by mybatis-generator.
     * @param introspectedTable the table.
     * @param baseDaoTypeName the full qualified name of the base dao.
     * @return dao interface of the table.
     */
    YobatisJavaFile tableSpecificDaoInterface(Interface interfaze, IntrospectedTable introspectedTable, String baseDaoTypeName);

    YobatisJavaFile tableSpecificDaoImpl(Interface specificDaoInterface, IntrospectedTable introspectedTable, GeneratedJavaFile baseDaoImpl);

    /**
     * Create base domain java file corresponding to the {@code introspectedTable}.
     * @param originalDomainClass the original domain class.
     * @param introspectedTable the table.
     * @return the base domain java file.
     */
    YobatisJavaFile baseDomain(TopLevelClass originalDomainClass, IntrospectedTable introspectedTable);

    YobatisJavaFile domain(TopLevelClass originalDomain, IntrospectedTable introspectedTable, GeneratedJavaFile baseDomainJavaFile);

    YobatisJavaFile baseCriteria(TopLevelClass topLevelClass, IntrospectedTable introspectedTable);

    YobatisJavaFile criteria(TopLevelClass originalExample, IntrospectedTable introspectedTable);
}
