package func.compoundkey.dao;

import func.compoundkey.model.CompoundKeyTable;
import func.compoundkey.model.criteria.CompoundKeyTableCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompoundKeyTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    long count(CompoundKeyTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int deleteByCriteria(CompoundKeyTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int deleteByPk(@Param("pk1") Integer pk1, @Param("pk2") String pk2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int insertAll(CompoundKeyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int insert(CompoundKeyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    List<CompoundKeyTable> selectByCriteria(CompoundKeyTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    CompoundKeyTable selectByPk(@Param("pk1") Integer pk1, @Param("pk2") String pk2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateByCriteria(@Param("record") CompoundKeyTable record, @Param("example") CompoundKeyTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateAllByCriteria(@Param("record") CompoundKeyTable record, @Param("example") CompoundKeyTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int update(CompoundKeyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compound_key_table
     *
     * @mbg.generated Thu Aug 16 13:35:24 CST 2018
     */
    int updateAll(CompoundKeyTable record);
}